import { Component } from '@angular/core';

@Component({
  selector: 'mat-searchbar-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  public demoList: string[] = FRUIT_LIST;
  public filteredList: string[] = structuredClone(FRUIT_LIST);

  public onFilterChange(value: string) {
    this.filteredList = structuredClone(
      this.demoList.filter((d) => d.toLowerCase().includes(value.toLowerCase()))
    );
  }
}

export const FRUIT_LIST: string[] = [
  'Apple',
  'Apricot',
  'Avocado',
  'Banana',
  'Bilberry',
  'Blackberry',
  'Blackcurrant',
  'Blueberry',
  'Boysenberry',
  'Currant',
  'Cherry',
  'Cherimoya',
  'Chico fruit',
  'Cloudberry',
  'Coconut',
  'Cranberry',
  'Cucumber',
  'Custard apple',
  'Damson',
  'Date',
  'Dragonfruit',
  'Durian',
  'Elderberry',
  'Feijoa',
  'Fig',
  'Goji berry',
  'Gooseberry',
  'Grape',
  'Raisin',
  'Grapefruit',
  'Guava',
  'Honeyberry',
  'Huckleberry',
  'Jabuticaba',
  'Jackfruit',
  'Jambul',
  'Jujube',
  'Juniper berry',
  'Kiwano',
  'Kiwifruit',
  'Kumquat',
  'Lemon',
  'Lime',
  'Loquat',
  'Longan',
  'Lychee',
  'Mango',
  'Mangosteen',
  'Marionberry',
  'Melon',
  'Cantaloupe',
  'Honeydew',
  'Watermelon',
  'Miracle fruit',
  'Mulberry',
  'Nectarine',
  'Nance',
  'Olive',
  'Orange',
  'Blood orange',
  'Clementine',
  'Mandarine',
  'Tangerine',
  'Papaya',
  'Passionfruit',
  'Peach',
  'Pear',
  'Persimmon',
  'Physalis',
  'Plantain',
  'Plum',
  'Prune',
  'Pineapple',
  'Plumcot',
  'Pomegranate',
  'Pomelo',
  'Purple mangosteen',
  'Quince',
  'Raspberry',
  'Salmonberry',
  'Rambutan',
  'Redcurrant',
  'Salal berry',
  'Salak',
  'Satsuma',
  'Soursop',
  'Star fruit',
  'Solanum quitoense',
  'Strawberry',
  'Tamarillo',
  'Tamarind',
  'Ugli fruit',
  'Yuzu',
];
